hub:
  image: selenium/hub
  ports:
    - "4444:4444"
firefox:
  image: selenium/node-firefox
  environment:
    NODE_MAX_INSTANCE: 2
    NODE_MAX_SESSION: 2
  links:
    - hub
chrome:
  image: selenium/node-chrome
  environment:
    NODE_MAX_INSTANCE: 2
    NODE_MAX_SESSION: 2
  links:
    - hub